version: '3.1'

services:
  github-runner:   
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GH_TOKEN=${GH_TOKEN}
        - GH_OWNER=${GH_OWNER}
        - GH_REPOSITORY=${GH_REPOSITORY}
        - GH_IS_ORGANISATION=${GH_IS_ORGANISATION}
      platforms: 
        - "linux/amd64"
    env_file:
      - .env

  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
