version: '3.1'

services:
  github-runner:   
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GH_TOKEN=${GH_TOKEN}
        - GH_OWNER=${GH_OWNER}
        - GH_REPOSITORY=${GH_REPOSITORY}
        - GH_IS_ORGANISATION=${GH_IS_ORGANISATION}
      platforms: 
        - "linux/amd64"
    env_file:
      - .env

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

  ngrok:
    image: ngrok/ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["http", "sonarqube:9000"]